name: loops
version: 3.4.0
date: 2017-10-27
description: |
    Computing with quasigroups and loops in GAP

authors:
    - name: Gabor Nagy
      url: http://www.math.u-szeged.hu/~nagyg/
    - name: Petr Vojtechovsky
      url: http://www.math.du.edu/~petr/

maintainers:
    - name: Gabor Nagy
      url: http://www.math.u-szeged.hu/~nagyg/
    - name: Petr Vojtechovsky
      url: http://www.math.du.edu/~petr/

GAP: ">=4.7"

www: http://www.math.du.edu/loops
readme: README.loops
packageinfo: http://www.math.du.edu/loops/PackageInfo.g

downloads:
    - name: -win.zip
      url: http://www.math.du.edu/loops/loops-3.4.0-win.zip
    - name: .tar.gz
      url: http://www.math.du.edu/loops/loops-3.4.0.tar.gz

abstract: |
    The LOOPS package provides researchers in nonassociative algebra with a computational tool that integrates standard notions of loop theory with libraries of loops and group-theoretical algorithms of GAP. The package also expands GAP toward nonassociative structures.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
